"""
Runtime mountain ranges module — no geopandas, no shapefile.

Loads data/ranges_lookup.json (generated by scripts/precompute_ranges.py) and
exposes search_range() for fuzzy name lookup.
"""

import json
from functools import lru_cache
from pathlib import Path

from rapidfuzz import fuzz, process

_LOOKUP_PATH = Path(__file__).parent.parent / "data" / "ranges_lookup.json"


@lru_cache(maxsize=1)
def _load_lookup() -> dict:
    with open(_LOOKUP_PATH, encoding="utf-8") as f:
        return json.load(f)


def _build_candidates(lookup: dict) -> list[tuple[str, int, str]]:
    """
    Returns (candidate_string, gmba_id, field) tuples for rapidfuzz matching.
    Each range contributes one entry per non-None name field and per local name.
    """
    rows = []
    for gmba_id_str, entry in lookup.items():
        gmba_id = int(gmba_id_str)
        for field in ("name_en", "name_fr", "name_de"):
            val = entry.get(field)
            if val:
                rows.append((val, gmba_id, field))
        for local in entry.get("local_names") or []:
            if local:
                rows.append((local, gmba_id, "local"))
    return rows


@lru_cache(maxsize=1)
def _candidates() -> list[tuple[str, int, str]]:
    return _build_candidates(_load_lookup())


def search_range(query: str, top_k: int = 5) -> list[dict]:
    """
    Fuzzy-match query against GMBA Basic polygon names.

    Returns up to top_k dicts:
        {gmba_id, name_en, centroid_lat, centroid_lon, score, matched_field, matched_name}
    sorted by descending match score.
    """
    candidates = _candidates()
    lookup = _load_lookup()

    strings = [c[0] for c in candidates]
    results = process.extract(query, strings, scorer=fuzz.WRatio, limit=top_k * 3)

    seen_ids: set[int] = set()
    out = []
    for matched_str, score, idx in results:
        _, gmba_id, field = candidates[idx]
        if gmba_id in seen_ids:
            continue
        seen_ids.add(gmba_id)
        entry = lookup[str(gmba_id)]
        out.append({
            "gmba_id":       gmba_id,
            "name_en":       entry.get("name_en"),
            "centroid_lat":  entry["centroid_lat"],
            "centroid_lon":  entry["centroid_lon"],
            "score":         score,
            "matched_field": field,
            "matched_name":  matched_str,
        })
        if len(out) == top_k:
            break

    return out
